# Generated by Django 5.2.1 on 2025-06-23 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddexamHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('noofrooms', models.PositiveIntegerField(null=True)),
                ('noofbenches', models.PositiveIntegerField(null=True)),
                ('total_benches', models.PositiveIntegerField(null=True)),
                ('total_seats', models.PositiveIntegerField(null=True)),
                ('rooms_list', models.CharField(max_length=255, null=True)),
                ('students_per_bench', models.IntegerField(choices=[(2, 'Two students per bench'), (3, 'Three students per bench')], null=True)),
            ],
            options={
                'db_table': 'AddexamHall',
            },
        ),
        migrations.CreateModel(
            name='AddFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=10, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('branch', models.CharField(max_length=10, null=True)),
                ('subject', models.CharField(max_length=10, null=True)),
                ('semester', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(upload_to='static\\faculty')),
                ('profilename', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Addfaculty',
            },
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('year', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('profile_url', models.URLField(null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'AddStudent',
            },
        ),
        migrations.CreateModel(
            name='AddTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('iv_cse_a_faculty', models.CharField(default='Prabhakara Rao', max_length=100, verbose_name='CSE A Faculty')),
                ('iv_cse_b_faculty', models.CharField(default='Akhila', max_length=100, verbose_name='CSE B Faculty')),
                ('iv_cse_c_faculty', models.CharField(default='SriLatha', max_length=100, verbose_name='CSE C Faculty')),
            ],
            options={
                'db_table': 'AddTimeTable',
            },
        ),
        migrations.CreateModel(
            name='AdminAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(null=True)),
                ('senderemail', models.EmailField(max_length=254, null=True)),
                ('annuncementdate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='Examallotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, null=True)),
                ('RoomNo', models.CharField(max_length=20, null=True)),
                ('BenchNo', models.CharField(max_length=20, null=True)),
                ('SeatNumber', models.CharField(max_length=20, null=True)),
                ('Student_Id', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'Examallotment',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
    ]
