# Generated by Django 5.2.1 on 2025-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexamhall',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='addexamhall',
            name='starttime',
        ),
        migrations.AddField(
            model_name='addexamhall',
            name='subject1',
            field=models.CharField(default='Not Specified', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexamhall',
            name='subject2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
