# Generated by Django 5.2.1 on 2025-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_addexamhall_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexamhall',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addexamhall',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
